name: CI
on:
  workflow_dispatch:
jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - name: Show log trigger
        run: echo "Triggered by ${{ github.event_name }}"
        
      - name: Second command
        run: echo "This is now a second command"
        
      - name: Multi line
        run: |
          echo "Triggered by ${{ github.event_name }}"
          echo "This is now a second command"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug file path
        run: |
          pwd
          ls -la
          
      - name: Upload aritfact
        uses: actions/upload-artifact@main
        with:
          name: test
          path: ./test
